name: 'JUnit XML to Slack'
description: 'Send condensed Junit report to Slack'
branding:
    icon: "bell"
    color: "green"
inputs:
  slack-webhook-url: 
    description: 'Webhook URL for Slack'
    required: true
  directory-path:
    description: 'Directory path to JUnit XML file'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
